### ISSUE TITLE
项目在idea 里面报错太多 gradle 不行啊

### ISSUE THREAD

**Issue by cx52** [mashirot/bilibili-live-comet-demo#1]
The project 'bilibili-live-comet-demo' is not a Gradle-based project

**Comment by ShiinaKin** [comment]
show me the log

**Comment by cx52** [comment]
![捕获](https://github.com/mashirot/bilibili-live-comet-demo/assets/63282983/5eca466a-0a95-4398-855e-a8601c91d9b0)
不知道是我网络问题还是哪里问题

**Comment by cx52** [comment]
请教一下，项目git后，然后进入自动配置，下载好腾讯云镜像gradle8.4，然后自动import，bulid，就会这样，是网络问题吗

**Comment by ShiinaKin** [comment]
![image](https://github.com/mashirot/bilibili-live-comet-demo/assets/52254895/91888b52-f104-46d2-9d7e-1f9cb62b8cad)
大概率是你的网络问题，你可以本地装一个gradle，不要用包装器

**Comment by ShiinaKin** [comment]
![image](https://github.com/mashirot/bilibili-live-comet-demo/assets/52254895/fafdd575-31dc-4e59-ab05-3d1a3bb4fc0b)
也许你可以点到这一层看看日志

**Comment by cx52** [comment]
好的，感谢回复啊，已经给您粉心了，项目目前是可以测试的把，感觉可能gradle插件不匹配，我再研究研究

**Comment by ShiinaKin** [comment]
是的，但现在uid和cookie是必填的，你自己填进去就行

**Comment by ShiinaKin** [comment]
![image](https://github.com/mashirot/bilibili-live-comet-demo/assets/52254895/4ace4a0a-7570-4da9-b752-0d11f90e6056)
